springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  profiles:
    include: ${ENV:local}

http:
  products:
    getById: "http://localhost:8081/api/v1/products/{id}"
  payments:
    requestPayment: "http://localhost:8082/api/v1/payments"
